# fly.toml app configuration file generated for golf-analytics-rmc on 2026-06-07T19:58:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'golf-analytics-rmc'
primary_region = 'lax'

[build]
  dockerfile = "shinyanalytics/Dockerfile"
  context = "shinyanalytics"
  #image = 'ghcr.io/eriklarsen4/golf-analytics:latest'

[processes]
  #app = "/usr/bin/shiny-server"
  app = "R -e \"port <- as.numeric(Sys.getenv('PORT', 3838)); shiny::runApp('/srv/shiny-server', host='0.0.0.0', port=port)\""

[http_service]
  internal_port = 3838
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpus = 1
  memory_mb = 1024

[registry]
  username = "eriklarsen4"
  password = "GHCR_PAT"
  
[env]
  PORT = "3838"