name: Build Golf-dev

on:
  push:
    branches: [ dev ]
    paths:
      - docker/Dockerfile.dev
      - python/**
      - R/**
      - DESCRIPTION
      - NAMESPACE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push golf-dev
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.dev
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/golf-dev:latest
