name: Build Golf-runtime

on:
  push:
    branches: [ dev ]
    paths:
      - docker/Dockerfile.runtime
      - inst/extdata/golf.duckdb
      - inst/predictions/**
      - R/**
      - DESCRIPTION
      - NAMESPACE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and push golf-runtime
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.runtime
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/golf-runtime:latest
